/**
 * Business Plan Tab Component - Main Entry Point
 */

"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Briefcase, Lock, AlertTriangle, CheckCircle, FileText, History, Edit3 } from "lucide-react"
import { useEffect, useState } from "react"

import type {
  BusinessPlanTabProps,
  BusinessPlanAssumptionsType,
  ScenarioType,
  ChangeLogEntryType,
  FrozenPlanType,
} from "./plan-tab/types"
import { calculateKPIs } from "./plan-tab/utils"
import { systemSuggestion } from "./plan-tab/mock-data"
import { SystemSuggestionCard } from "./plan-tab/system-suggestion-card"
import { InteractiveControls } from "./plan-tab/interactive-controls"
import { KPIMetricsCard } from "./plan-tab/kpi-metrics-card"
import { ScenariosSection } from "./plan-tab/scenarios-section"

/**
 * Property interface representing a real estate investment property
 */
interface Property {
  id: string
  name: string
  address: string
  isActive: boolean
}

/**
 * Key Performance Indicators for investment analysis
 */
interface KPIMetrics {
  /** Internal Rate of Return as percentage */
  irr: number
  /** Equity multiple (total return / initial equity) */
  equityMultiple: number
  /** Cash-on-cash return as percentage */
  cashOnCash: number
  /** Debt Service Coverage Ratio */
  dscr: number
  /** Payback period in years */
  payback: number
}

/**
 * Business Plan Tab Component
 *
 * Main component for managing real estate investment business plans with interactive
 * controls, real-time calculations, and comprehensive scenario management.
 */
export function PlanTab({ property }: BusinessPlanTabProps) {
  /** Current business plan assumptions */
  const [assumptions, setAssumptions] = useState<BusinessPlanAssumptionsType>({
    holdPeriod: 5,
    renovationBudget: 10000,
    renovationTiming: "upfront",
    financingMix: 75, // 75% equity, 25% debt
    exitCap: 5.25,
    rentGrowth: "base",
  })

  /** Array of saved scenarios for comparison */
  const [scenarios, setScenarios] = useState<ScenarioType[]>([])

  /** Whether the business plan is frozen for execution */
  const [isPlanFrozen, setIsPlanFrozen] = useState(false)

  /** User notes for the business plan */
  const [notes, setNotes] = useState("")

  /** Change log entries for audit trail */
  const [changeLog, setChangeLog] = useState<ChangeLogEntryType[]>([])

  // Dialog and sheet visibility states
  const [showSaveDialog, setShowSaveDialog] = useState(false)
  const [showComparisonSheet, setShowComparisonSheet] = useState(false)
  const [showFreezeDialog, setShowFreezeDialog] = useState(false)
  const [showNotesDialog, setShowNotesDialog] = useState(false)
  const [showChangeLogSheet, setShowChangeLogSheet] = useState(false)

  /** Frozen plan data when plan is locked */
  const [frozenPlan, setFrozenPlan] = useState<FrozenPlanType | null>(null)

  /**
   * Calculate Key Performance Indicators based on business plan assumptions
   *
   * Uses simplified financial modeling to estimate investment returns.
   * In a production system, this would integrate with sophisticated
   * financial modeling engines and market data.
   *
   * @param assumptions - The business plan assumptions to calculate from
   * @returns Calculated KPI metrics
   */
  const currentMetrics = calculateKPIs(assumptions)

  /**
   * AI-generated system suggestion for optimal business plan
   *
   * In production, this would be generated by machine learning models
   * analyzing market conditions, comparable properties, and risk factors.
   */
  // Replaced with imported systemSuggestion

  /**
   * Add an entry to the change log for audit trail
   *
   * @param action - Type of action performed
   * @param description - Description of the change
   * @param oldValue - Previous value (optional)
   * @param newValue - New value (optional)
   */
  const addToChangeLog = (action: string, description: string, oldValue?: any, newValue?: any) => {
    const entry: ChangeLogEntryType = {
      id: Date.now().toString(),
      action,
      description,
      timestamp: new Date(),
      oldValue,
      newValue,
    }
    setChangeLog((prev) => [entry, ...prev])
  }

  /**
   * Update a specific assumption and log the change
   *
   * @param key - The assumption key to update
   * @param value - The new value
   */
  const updateAssumptions = (key: keyof BusinessPlanAssumptionsType, value: any) => {
    const oldValue = assumptions[key]
    setAssumptions((prev) => ({ ...prev, [key]: value }))

    if (oldValue !== value) {
      addToChangeLog("Assumption Updated", `${key.charAt(0).toUpperCase() + key.slice(1)} changed`, oldValue, value)
    }
  }

  // --- New: load scenarios for current logged-in user from API on mount ---
  useEffect(() => {
    let mounted = true
    async function loadScenarios() {
      try {
        const res = await fetch("/api/scenarios", { method: "GET" })
        if (!res.ok) {
          const text = await res.text().catch(() => "")
          console.error("Failed to load scenarios:", res.status, text)
          return
        }
        const json = await res.json()
        const mapped: ScenarioType[] = (json.scenarios || []).map((row: any) => {
          const payload = row.payload || {}
          return {
            id: String(row.id),
            name: row.name,
            assumptions: payload.assumptions || {},
            metrics: payload.metrics || {},
            createdAt: row.created_at ? new Date(row.created_at) : new Date(),
          }
        })
        if (mounted) setScenarios(mapped)
      } catch (err) {
        console.error("loadScenarios error:", err)
      }
    }
    loadScenarios()
    return () => {
      mounted = false
    }
  }, [])

  /**
   * Save the current assumptions and metrics as a named scenario
   *
   * This now POSTS to /api/scenarios and stores owner on server using Clerk user id.
   * The UI still updates locally and logs the change as before.
   */
  const saveScenario = async (name: string) => {
    // keep local behavior: create scenario object (optimistic-ish)
    const localScenario: ScenarioType = {
      id: Date.now().toString(),
      name,
      assumptions: { ...assumptions },
      metrics: calculateKPIs(assumptions),
      createdAt: new Date(),
    }

    // optimistic add to UI so user sees it instantly
    setScenarios((prev) => [localScenario, ...prev])
    addToChangeLog("Scenario Saved", `Created new scenario: ${name}`)

    // send to server to persist (server will set owner_id from Clerk)
    try {
      const payload = { assumptions: localScenario.assumptions, metrics: localScenario.metrics }
      const res = await fetch("/api/scenarios", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, description: "", payload }),
      })

      if (!res.ok) {
        const errText = await res.text().catch(() => "")
        console.error("Failed to save scenario on server:", res.status, errText)
        // optional: remove optimistic scenario if server fails
        // setScenarios(prev => prev.filter(s => s !== localScenario))
        return
      }

      const json = await res.json()
      const saved = json.scenario

      // Replace optimistic local scenario with server-side row (id, timestamps, payload)
      setScenarios((prev) => {
        // remove the optimistic one we added (match by name + createdAt heuristic)
        const withoutOptimistic = prev.filter((s) => !(s.name === localScenario.name && s.createdAt === localScenario.createdAt))
        const mapped: ScenarioType = {
          id: String(saved.id),
          name: saved.name,
          assumptions: saved.payload?.assumptions || payload.assumptions,
          metrics: saved.payload?.metrics || payload.metrics,
          createdAt: saved.created_at ? new Date(saved.created_at) : new Date(),
        }
        return [mapped, ...withoutOptimistic]
      })
    } catch (err) {
      console.error("saveScenario request error:", err)
    }
  }

  /**
   * Delete a saved scenario
   *
   * Now calls DELETE /api/scenarios/:id and removes locally on success.
   * Change log remains in place.
   */
  const deleteScenario = async (scenarioId: string) => {
    const scenario = scenarios.find((s) => s.id === scenarioId)

    // optimistic UI update: remove locally immediately
    setScenarios((prev) => prev.filter((s) => s.id !== scenarioId))

    try {
      const res = await fetch(`/api/scenarios/${scenarioId}`, { method: "DELETE" })
      if (!res.ok) {
        const txt = await res.text().catch(() => "")
        console.error("delete failed:", res.status, txt)
        // revert UI removal if needed: re-add scenario
        if (scenario) setScenarios((prev) => [scenario, ...prev])
        return
      }
      if (scenario) addToChangeLog("Scenario Deleted", `Removed scenario: ${scenario.name}`)
    } catch (err) {
      console.error("deleteScenario error:", err)
      if (scenario) setScenarios((prev) => [scenario, ...prev])
    }
  }

  /**
   * Freeze the current business plan for execution
   *
   * Creates a locked snapshot of the current plan that cannot be modified
   * without explicit unfreezing. Used when plan is ready for implementation.
   */
  const freezePlan = () => {
    const frozenData = {
      assumptions: { ...assumptions },
      metrics: calculateKPIs(assumptions),
      frozenAt: new Date(),
    }

    setFrozenPlan(frozenData)
    setIsPlanFrozen(true)
    setShowFreezeDialog(false)

    addToChangeLog("Plan Frozen", "Business plan finalized and locked for execution", null, frozenData)
  }

  /**
   * Unfreeze the business plan to allow modifications
   */
  const unfreezePlan = () => {
    setIsPlanFrozen(false)
    setFrozenPlan(null)

    addToChangeLog("Plan Unfrozen", "Business plan unlocked for further modifications")
  }

  /**
   * Save business plan notes and log the change
   */
  const saveNotes = () => {
    addToChangeLog("Notes Updated", "Business plan notes were modified")
    setShowNotesDialog(false)
  }

  if (!property) {
    return (
      <div className="bg-white rounded-2xl shadow-lg border-2 border-white p-4 text-center">
        <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <Briefcase className="w-8 h-8 text-gray-400" />
        </div>
        <h2 className="text-base font-bold text-gray-900 mb-2">Business Plan</h2>
        <p className="text-sm text-gray-600">Select a property to view business plan details.</p>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {/* Main Header Card with Action Buttons */}
      <Card className="bg-white rounded-2xl shadow-lg border-2 border-white">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-gray-100 rounded-lg">
                <Briefcase className="w-5 h-5 sm:w-6 sm:h-6 text-gray-600" />
              </div>
              <div>
                <CardTitle className="text-sm font-bold text-gray-900">Business Plan Suggestions</CardTitle>
                <p className="text-xs sm:text-sm text-gray-600">
                  AI-driven plan for maximizing returns. Adjust assumptions to refine strategy.
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {/* Plan Status Badge */}
              {isPlanFrozen && (
                <Badge variant="secondary" className="bg-gray-100 text-gray-800 text-xs">
                  <Lock className="w-3 h-3 mr-1" />
                  Finalized
                </Badge>
              )}

              {/* Notes Dialog */}
              <Dialog open={showNotesDialog} onOpenChange={setShowNotesDialog}>
                <DialogTrigger asChild>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="text-gray-600 border-gray-200 hover:bg-gray-50 bg-transparent"
                  >
                    <FileText className="w-4 h-4" />
                  </Button>
                </DialogTrigger>
                <DialogContent className="max-w-2xl">
                  <DialogHeader>
                    <DialogTitle>Business Plan Notes</DialogTitle>
                  </DialogHeader>
                  <div className="space-y-4">
                    <div>
                      <Label htmlFor="notes">
                        Add notes, assumptions, or key considerations for this business plan:
                      </Label>
                      <Textarea
                        id="notes"
                        value={notes}
                        onChange={(e) => setNotes(e.target.value)}
                        placeholder="Enter your notes here..."
                        className="min-h-[200px] mt-2"
                      />
                    </div>
                    <div className="flex justify-end gap-2">
                      <Button variant="outline" onClick={() => setShowNotesDialog(false)}>
                        Cancel
                      </Button>
                      <Button onClick={saveNotes}>Save Notes</Button>
                    </div>
                  </div>
                </DialogContent>
              </Dialog>

              {/* Change Log Sheet */}
              <Sheet open={showChangeLogSheet} onOpenChange={setShowChangeLogSheet}>
                <SheetTrigger asChild>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="text-gray-600 border-gray-200 hover:bg-gray-50 bg-transparent"
                  >
                    <History className="w-4 h-4" />
                  </Button>
                </SheetTrigger>
                <SheetContent side="right" className="w-full sm:max-w-2xl">
                  <SheetHeader>
                    <SheetTitle>Change Log</SheetTitle>
                  </SheetHeader>
                  <div className="mt-6">
                    {changeLog.length === 0 ? (
                      <div className="text-center py-8">
                        <History className="w-12 h-12 text-gray-300 mx-auto mb-4" />
                        <p className="text-gray-500">No changes recorded yet</p>
                        <p className="text-xs text-gray-400 mt-1">
                          Changes will appear here as you modify the business plan
                        </p>
                      </div>
                    ) : (
                      <div className="space-y-4">
                        {changeLog.map((entry) => (
                          <div key={entry.id} className="border border-gray-200 rounded-lg p-4">
                            <div className="flex items-start justify-between mb-2">
                              <div className="flex items-center gap-2">
                                <div
                                  className={`w-2 h-2 rounded-full ${
                                    entry.action === "Plan Frozen"
                                      ? "bg-gray-600"
                                      : entry.action === "Plan Unfrozen"
                                        ? "bg-gray-500"
                                        : entry.action === "Scenario Saved"
                                          ? "bg-gray-700"
                                          : entry.action === "Scenario Deleted"
                                            ? "bg-gray-400"
                                            : "bg-gray-500"
                                  }`}
                                />
                                <span className="text-sm font-semibold text-gray-900">{entry.action}</span>
                              </div>
                              <span className="text-xs text-gray-500">
                                {entry.timestamp.toLocaleDateString()} {entry.timestamp.toLocaleTimeString()}
                              </span>
                            </div>
                            <p className="text-sm text-gray-700 mb-2">{entry.description}</p>

                            {/* Show before/after values for changes */}
                            {entry.oldValue !== undefined && entry.newValue !== undefined && (
                              <div className="bg-gray-50 rounded p-2 text-xs">
                                <div className="flex gap-4">
                                  <div>
                                    <span className="text-gray-600 font-medium">From:</span>
                                    <span className="ml-1">
                                      {typeof entry.oldValue === "object"
                                        ? JSON.stringify(entry.oldValue)
                                        : String(entry.oldValue)}
                                    </span>
                                  </div>
                                  <div>
                                    <span className="text-gray-800 font-medium">To:</span>
                                    <span className="ml-1">
                                      {typeof entry.newValue === "object"
                                        ? JSON.stringify(entry.newValue)
                                        : String(entry.newValue)}
                                    </span>
                                  </div>
                                </div>
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </SheetContent>
              </Sheet>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Business Plan Notes Display */}
      {notes && (
        <Card className="bg-gray-50 rounded-2xl shadow-lg border-2 border-gray-200">
          <CardHeader className="p-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-gray-100 rounded-lg">
                  <FileText className="w-6 h-6 text-gray-600" />
                </div>
                <div>
                  <CardTitle className="text-sm font-bold text-gray-900">Business Plan Notes</CardTitle>
                  <p className="text-xs text-gray-700">Key considerations and assumptions</p>
                </div>
              </div>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => setShowNotesDialog(true)}
                className="text-gray-600 hover:bg-gray-100"
              >
                <Edit3 className="w-4 h-4" />
              </Button>
            </div>
          </CardHeader>
          <CardContent className="p-3">
            <div className="bg-white rounded-lg p-3 border border-gray-200">
              <p className="text-sm text-gray-700 whitespace-pre-wrap">{notes}</p>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Frozen Plan Display */}
      {isPlanFrozen && frozenPlan && (
        <Card className="bg-gray-50 rounded-2xl shadow-lg border-2 border-gray-200">
          <CardHeader className="p-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-gray-100 rounded-lg">
                  <CheckCircle className="w-6 h-6 text-gray-600" />
                </div>
                <div>
                  <CardTitle className="text-sm font-bold text-gray-900">Frozen Business Plan</CardTitle>
                  <p className="text-xs text-gray-700">
                    Plan finalized on {frozenPlan.frozenAt.toLocaleDateString()} at{" "}
                    {frozenPlan.frozenAt.toLocaleTimeString()}
                  </p>
                </div>
              </div>
              <Badge className="bg-gray-600 text-white text-xs">
                <Lock className="w-3 h-3 mr-1" />
                Execution Ready
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="p-3">
            {/* Frozen Plan KPIs */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
              <div className="bg-white rounded-lg p-2 border border-gray-200">
                <div className="text-base font-bold text-gray-800">{frozenPlan.metrics.irr.toFixed(1)}%</div>
                <div className="text-xs text-gray-600">Target IRR</div>
              </div>
              <div className="bg-white rounded-lg p-2 border border-gray-200">
                <div className="text-base font-bold text-gray-800">{frozenPlan.metrics.equityMultiple.toFixed(2)}x</div>
                <div className="text-xs text-gray-600">Equity Multiple</div>
              </div>
              <div className="bg-white rounded-lg p-2 border border-gray-200">
                <div className="text-base font-bold text-gray-800">{frozenPlan.metrics.cashOnCash.toFixed(1)}%</div>
                <div className="text-xs text-gray-600">Cash-on-Cash</div>
              </div>
              <div className="bg-white rounded-lg p-2 border border-gray-200">
                <div className="text-base font-bold text-gray-800">{frozenPlan.assumptions.holdPeriod} years</div>
                <div className="text-xs text-gray-600">Hold Period</div>
              </div>
            </div>

            {/* Execution Parameters */}
            <div className="p-3 bg-white rounded-lg border border-gray-200">
              <h4 className="text-sm font-semibold text-gray-900 mb-2">Execution Parameters</h4>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3 text-xs">
                <div>
                  <span className="text-gray-600">Renovation Budget:</span>
                  <span className="font-medium ml-2">
                    ${frozenPlan.assumptions.renovationBudget.toLocaleString()}/unit
                  </span>
                </div>
                <div>
                  <span className="text-gray-600">Renovation Timing:</span>
                  <span className="font-medium ml-2 capitalize">{frozenPlan.assumptions.renovationTiming}</span>
                </div>
                <div>
                  <span className="text-gray-600">Financing Mix:</span>
                  <span className="font-medium ml-2">{frozenPlan.assumptions.financingMix}% equity</span>
                </div>
                <div>
                  <span className="text-gray-600">Exit Cap Rate:</span>
                  <span className="font-medium ml-2">{frozenPlan.assumptions.exitCap.toFixed(2)}%</span>
                </div>
                <div>
                  <span className="text-gray-600">Rent Growth:</span>
                  <span className="font-medium ml-2 capitalize">{frozenPlan.assumptions.rentGrowth}</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* AI System Suggestions Card */}
      <SystemSuggestionCard suggestion={systemSuggestion} />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Interactive Plan Controls */}
        <InteractiveControls
          assumptions={assumptions}
          isPlanFrozen={isPlanFrozen}
          onUpdateAssumptions={updateAssumptions}
        />

        {/* Real-time KPIs Display */}
        <KPIMetricsCard
          currentMetrics={currentMetrics}
          systemSuggestion={systemSuggestion}
          isPlanFrozen={isPlanFrozen}
          onSaveScenario={saveScenario}
        />
      </div>

      {/* Saved Scenarios section */}
      <ScenariosSection scenarios={scenarios} onDeleteScenario={deleteScenario} onLoadScenario={setAssumptions} />

      {/* Freeze/Unfreeze Plan Button */}
      <div className="flex justify-center pt-4">
        {isPlanFrozen ? (
          <Button
            size="lg"
            variant="outline"
            onClick={unfreezePlan}
            className="text-gray-600 border-gray-200 hover:bg-gray-50 bg-transparent"
          >
            <Lock className="w-4 h-4 mr-2" />
            Unfreeze Plan
          </Button>
        ) : (
          <Dialog open={showFreezeDialog} onOpenChange={setShowFreezeDialog}>
            <DialogTrigger asChild>
              <Button size="lg" className="bg-gray-600 hover:bg-gray-700 text-white">
                <CheckCircle className="w-4 h-4 mr-2" />
                Freeze Plan
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-amber-500" />
                  Freeze Business Plan
                </DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg">
                  <p className="text-sm text-amber-800 mb-2">
                    <strong>Warning:</strong> Freezing this plan will:
                  </p>
                  <ul className="text-sm text-amber-700 space-y-1 ml-4">
                    <li>• Lock all current assumptions and projections</li>
                    <li>• Disable editing of controls</li>
                    <li>• Create a permanent record for execution</li>
                    <li>• Require manual unfreezing to make changes</li>
                  </ul>
                </div>

                <div className="p-4 bg-gray-50 border border-gray-200 rounded-lg">
                  <h4 className="text-sm font-semibold text-gray-900 mb-2">Current Plan Summary:</h4>
                  <div className="grid grid-cols-2 gap-3 text-sm">
                    <div>
                      <span className="text-gray-700">Hold Period:</span>
                      <span className="font-medium ml-2">{assumptions.holdPeriod} years</span>
                    </div>
                    <div>
                      <span className="text-gray-700">Renovation:</span>
                      <span className="font-medium ml-2">${assumptions.renovationBudget.toLocaleString()}/unit</span>
                    </div>
                    <div>
                      <span className="text-gray-700">IRR:</span>
                      <span className="font-bold text-gray-800 ml-2">{currentMetrics.irr.toFixed(1)}%</span>
                    </div>
                    <div>
                      <span className="text-gray-700">Equity Multiple:</span>
                      <span className="font-bold text-gray-800 ml-2">{currentMetrics.equityMultiple.toFixed(2)}x</span>
                    </div>
                  </div>
                </div>

                <div className="flex justify-end gap-2">
                  <Button variant="outline" onClick={() => setShowFreezeDialog(false)}>
                    Cancel
                  </Button>
                  <Button onClick={freezePlan} className="bg-gray-600 hover:bg-gray-700">
                    <CheckCircle className="w-4 h-4 mr-2" />
                    Confirm Freeze
                  </Button>
                </div>
              </div>
            </DialogContent>
          </Dialog>
        )}
      </div>
    </div>
  )
}
