import type { CategoryData } from "./types"
import type { PropertyData } from "@/lib/property-data"
import { generateMonthlyData } from "./utils"

export const initializeProFormaData = (prop: PropertyData): CategoryData[] => {
  const units = prop.units || 100
  const marketRent = prop.unitMix?.[1]?.marketRent || 2000

  return [
    {
      id: "income",
      title: "GROSS POTENTIAL INCOME",
      expanded: true,
      color: "border-green-500",
      items: [
        {
          id: "market-rent",
          label: "Market Rent",
          category: "Rental Income",
          inPlace: marketRent * units * 12,
          yourUnderwriting: marketRent * 1.05 * units * 12,
          inputMode: "perUnit",
          inputType: "dollar",
          isEditable: true,
          growthRate: 3.0,
          monthlyData: generateMonthlyData(marketRent * units * 12),
          documentTotal: marketRent * units * 12,
        },
        {
          id: "loss-to-lease",
          label: "Loss to Lease",
          category: "Rental Income",
          inPlace: -marketRent * units * 12 * 0.02,
          yourUnderwriting: -marketRent * units * 12 * 0.03,
          inputMode: "total",
          inputType: "percent",
          percentBase: "PGI",
          isEditable: true,
          growthRate: 0,
          monthlyData: generateMonthlyData(-marketRent * units * 12 * 0.02),
          documentTotal: -marketRent * units * 12 * 0.02,
        },
        {
          id: "vacancy",
          label: "Vacancy Loss",
          category: "Rental Income",
          inPlace: -marketRent * units * 12 * 0.03,
          yourUnderwriting: -marketRent * units * 12 * 0.05,
          inputMode: "total",
          inputType: "percent",
          percentBase: "PGI",
          isEditable: true,
          growthRate: 0,
          monthlyData: generateMonthlyData(-marketRent * units * 12 * 0.03),
          documentTotal: -marketRent * units * 12 * 0.03,
        },
        {
          id: "concessions",
          label: "Concessions",
          category: "Rental Income",
          inPlace: -marketRent * units * 12 * 0.01,
          yourUnderwriting: -marketRent * units * 12 * 0.02,
          inputMode: "total",
          inputType: "dollar",
          isEditable: true,
          growthRate: 0,
          monthlyData: generateMonthlyData(-marketRent * units * 12 * 0.01),
          documentTotal: -marketRent * units * 12 * 0.01,
        },
        {
          id: "other-income",
          label: "Other Income",
          category: "Other Income",
          inPlace: units * 300 * 12,
          yourUnderwriting: units * 350 * 12,
          inputMode: "perUnit",
          inputType: "dollar",
          isEditable: true,
          growthRate: 2.0,
          monthlyData: generateMonthlyData(units * 300 * 12),
          documentTotal: units * 300 * 12,
        },
        {
          id: "egi",
          label: "EFFECTIVE GROSS INCOME",
          category: "",
          inPlace: marketRent * units * 12 * 0.94 + units * 300 * 12,
          yourUnderwriting: marketRent * 1.05 * units * 12 * 0.95 + units * 350 * 12,
          inputMode: "total",
          inputType: "dollar",
          isEditable: false,
          isSubtotal: true,
          formula: "= Market Rent - Loss to Lease - Vacancy - Concessions + Other Income",
        },
      ],
    },
    {
      id: "expenses",
      title: "OPERATING EXPENSES",
      expanded: true,
      color: "border-red-500",
      items: [
        {
          id: "property-taxes",
          label: "Property Taxes",
          category: "Non-Controllable",
          inPlace: units * 1200,
          yourUnderwriting: units * 1400,
          inputMode: "perUnit",
          inputType: "dollar",
          isEditable: true,
          growthRate: 3.0,
          monthlyData: generateMonthlyData(units * 1200),
          documentTotal: units * 1200,
        },
        {
          id: "insurance",
          label: "Insurance",
          category: "Non-Controllable",
          inPlace: units * 400,
          yourUnderwriting: units * 500,
          inputMode: "perUnit",
          inputType: "dollar",
          isEditable: true,
          growthRate: 5.0,
          monthlyData: generateMonthlyData(units * 400),
          documentTotal: units * 400,
        },
        {
          id: "management-fee",
          label: "Management Fee",
          category: "Controllable",
          inPlace: marketRent * units * 12 * 0.94 * 0.025,
          yourUnderwriting: marketRent * 1.05 * units * 12 * 0.95 * 0.03,
          inputMode: "total",
          inputType: "percent",
          percentBase: "EGI",
          isEditable: true,
          growthRate: 0,
          monthlyData: generateMonthlyData(marketRent * units * 12 * 0.94 * 0.025),
          documentTotal: marketRent * units * 12 * 0.94 * 0.025,
        },
        {
          id: "repairs-maintenance",
          label: "Repairs & Maintenance",
          category: "Controllable",
          inPlace: units * 800,
          yourUnderwriting: units * 900,
          inputMode: "perUnit",
          inputType: "dollar",
          isEditable: true,
          growthRate: 2.5,
          monthlyData: generateMonthlyData(units * 800),
          documentTotal: units * 800,
        },
        {
          id: "utilities",
          label: "Utilities",
          category: "Controllable",
          inPlace: units * 600,
          yourUnderwriting: units * 650,
          inputMode: "perUnit",
          inputType: "dollar",
          isEditable: true,
          growthRate: 3.5,
          monthlyData: generateMonthlyData(units * 600),
          documentTotal: units * 600,
        },
        {
          id: "payroll",
          label: "Payroll",
          category: "Controllable",
          inPlace: units * 500,
          yourUnderwriting: units * 550,
          inputMode: "perUnit",
          inputType: "dollar",
          isEditable: true,
          growthRate: 3.0,
          monthlyData: generateMonthlyData(units * 500),
          documentTotal: units * 500,
        },
        {
          id: "total-expenses",
          label: "TOTAL OPERATING EXPENSES",
          category: "",
          inPlace: units * (1200 + 400 + 800 + 600 + 500) + marketRent * units * 12 * 0.94 * 0.025,
          yourUnderwriting: units * (1400 + 500 + 900 + 650 + 550) + marketRent * 1.05 * units * 12 * 0.95 * 0.03,
          inputMode: "total",
          inputType: "dollar",
          isEditable: false,
          isSubtotal: true,
          formula: "= Sum of all operating expenses",
        },
      ],
    },
    {
      id: "noi",
      title: "NET OPERATING INCOME",
      expanded: true,
      color: "border-blue-500",
      items: [
        {
          id: "noi-value",
          label: "NET OPERATING INCOME",
          category: "",
          inPlace:
            marketRent * units * 12 * 0.94 +
            units * 300 * 12 -
            (units * (1200 + 400 + 800 + 600 + 500) + marketRent * units * 12 * 0.94 * 0.025),
          yourUnderwriting:
            marketRent * 1.05 * units * 12 * 0.95 +
            units * 350 * 12 -
            (units * (1400 + 500 + 900 + 650 + 550) + marketRent * 1.05 * units * 12 * 0.95 * 0.03),
          inputMode: "total",
          inputType: "dollar",
          isEditable: false,
          isSubtotal: true,
          formula: "= Effective Gross Income - Total Operating Expenses",
        },
      ],
    },
  ]
}
