/**
 * Sample Rent Roll Data for v0 development/fallback
 * Used when the actual REX API fails or during development
 */

export const sampleRentRollDocument = {
  "success": true,
  "document": {
    "id": 8,
    "user_id": "user_bypass_12345",
    "process_id": "f0325b31-10fc-401d-bf1c-507bea69b8ec",
    "document_id": "0ba54f65-a0dd-4f38-97d0-e9ee328b64b7",
    "filename": "1 page.pdf",
    "document_type": "rent_roll",
    "file_size": "87440",
    "upload_status": "pending",
    "extraction_status": "completed",
    "extraction_result": {
      "data": {
        "summary": {
          "asOfDate": "03/20/2019",
          "fileName": "1 page.pdf",
          "totalUnits": 14,
          "processedAt": "2025-12-15T07:34:40.636967+00:00",
          "documentType": "rent_roll",
          "propertyType": "multifamily"
        },
        "metadata": {
          "tokensUsed": 0,
          "clientReference": "UPLOAD-1765783973224",
          "processingTimeMs": null
        },
        "extraction": {
          "units": [
            [
              "Occupied",
              "9999",
              "10.00",
              "10/31/2019",
              "N/A",
              "1,057.00",
              "B2",
              "08/01/2018",
              "main_building",
              "1,177.00",
              "1238",
              "Yetter, Barry",
              "04/25/2008",
              "15-101",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "1,112.00",
              "1,112.00",
              "0.00",
              "55.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied-NTVL",
              "0.00",
              "0.00",
              "03/31/2019",
              "N/A",
              "845.00",
              "A1",
              "03/23/2018",
              "main_building",
              "985.00",
              "936",
              "Eyler, Alicia",
              "03/23/2018",
              "15-102",
              "03/31/2019",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "930.00",
              "930.00",
              "N/A",
              "35.00",
              "50.00",
              "N/A"
            ],
            [
              "Applicant",
              "99.00 *",
              "0.00",
              "07/31/2020",
              "N/A",
              "930.00 *",
              "B2",
              "04/29/2019",
              "main_building",
              "1,192.00",
              "1238",
              "Paul, Nicole",
              "04/29/2019",
              "15-103",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "1,035.00 *",
              "1,035.00 *",
              "N/A",
              "55.00 *",
              "N/A",
              "50.00 *"
            ],
            [
              "Admin/Down VACANT",
              "65.00 *",
              "N/A",
              "N/A",
              "N/A",
              "0.00 *",
              "A2",
              "N/A",
              "main_building",
              "1,000.00",
              "936",
              "VACANT",
              "N/A",
              "15-104",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "0.00",
              "0.00",
              "N/A",
              "55.00 *",
              "N/A",
              "N/A"
            ],
            [
              "Occupied",
              "3.00",
              "0.00",
              "07/31/2019",
              "N/A",
              "967.00",
              "B1",
              "07/20/2018",
              "main_building",
              "1,077.00",
              "1238",
              "Taylor, Maurice",
              "07/20/2018",
              "15-105",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "1,012.00",
              "1,012.00",
              "0.00",
              "45.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied",
              "0.00",
              "0.00",
              "08/31/2019",
              "N/A",
              "820.00",
              "A1",
              "06/01/2018",
              "main_building",
              "910.00",
              "936",
              "Fitts, Michael",
              "02/24/2012",
              "15-106",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "865.00",
              "865.00",
              "0.00",
              "45.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied",
              "0.00",
              "0.00",
              "02/29/2020",
              "N/A",
              "1,027.00",
              "B1",
              "02/23/2019",
              "main_building",
              "1,092.00",
              "1238",
              "Huggins, Jon",
              "02/23/2019",
              "15-107",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "1,092.00",
              "1,092.00",
              "0.00",
              "65.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied",
              "(159.33)",
              "0.00",
              "02/29/2020",
              "N/A",
              "920.00",
              "A2",
              "03/01/2019",
              "main_building",
              "975.00",
              "936",
              "Brown, Eric",
              "02/23/2018",
              "15-108",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "975.00",
              "975.00",
              "0.00",
              "55.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied",
              "(37.00)",
              "0.00",
              "11/30/2018",
              "N/A",
              "1,022.00",
              "B1",
              "12/01/2017",
              "main_building",
              "1,087.00",
              "1238",
              "McMullen, Kimberly",
              "10/09/2015",
              "15-109",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "1,087.00",
              "1,087.00",
              "0.00",
              "65.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied",
              "0.00",
              "0.00",
              "07/31/2019",
              "N/A",
              "855.00",
              "A1",
              "08/01/2018",
              "main_building",
              "910.00",
              "936",
              "Saftner, Christopher",
              "07/14/2017",
              "15-110",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "950.00",
              "950.00",
              "N/A",
              "45.00",
              "N/A",
              "50.00"
            ],
            [
              "Occupied",
              "0.00",
              "0.00",
              "11/30/2019",
              "N/A",
              "1,047.00",
              "B1",
              "12/01/2018",
              "main_building",
              "1,102.00",
              "1238",
              "McCarley, Nichola",
              "11/17/2017",
              "15-111",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "1,102.00",
              "1,102.00",
              "0.00",
              "55.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied",
              "0.00",
              "0.00",
              "09/30/2019",
              "N/A",
              "870.00",
              "A1",
              "10/01/2018",
              "main_building",
              "925.00",
              "936",
              "Dugan, Elizabeth",
              "09/24/2010",
              "15-112",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "925.00",
              "925.00",
              "0.00",
              "55.00",
              "N/A",
              "N/A"
            ],
            [
              "Occupied-NTV",
              "(120.00)",
              "0.00",
              "04/30/2019",
              "N/A",
              "845.00",
              "A1",
              "04/28/2018",
              "main_building",
              "985.00",
              "936",
              "Hamer, Deborah",
              "04/28/2018",
              "15-113",
              "04/30/2019",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "930.00",
              "930.00",
              "N/A",
              "35.00",
              "50.00",
              "N/A"
            ],
            [
              "Occupied",
              "145.00",
              "0.00",
              "12/31/2019",
              "N/A",
              "1,162.00",
              "B2",
              "12/18/2018",
              "main_building",
              "1,227.00",
              "1238",
              "Schollaert, Toni",
              "12/18/2018",
              "15-114",
              "N/A",
              "intermark management corporation - redacted property",
              "N/A",
              "N/A",
              "1,227.00",
              "1,227.00",
              "0.00",
              "N/A",
              "N/A",
              "N/A"
            ]
          ],
          "headers": [
            "status",
            "balance",
            "deposit",
            "End Date",
            "Unit_Type",
            "base_rent",
            "Floor Plan",
            "Start Date",
            "Building Id",
            "Market Rent",
            "Square Feet",
            "Tenant Name",
            "Move In Date",
            "Suite Number",
            "Move Out Date",
            "Property Name",
            "Month To Month",
            "Lease Description",
            "Total Charges Paid",
            "total_contractual_rent",
            "RENT",
            "WATER",
            "Unit Upgrades",
            "WASH/DRY"
          ]
        },
        "metadataMappings": {
          "As of Date": "03/20/2019",
          "Asset Type": "Multifamily",
          "Occupancy Mapping": {
            "Occupied": "Occupied",
            "Applicant": "Non-revenue",
            "validation": {
              "unmapped_statuses": [],
              "all_statuses_mapped": true
            },
            "Occupied-NTV": "Occupied",
            "Occupied-NTVL": "Occupied",
            "Admin/Down VACANT": "Vacant"
          },
          "Transaction Codes": [
            "RENT",
            "WATER",
            "Unit Upgrades",
            "WASH/DRY"
          ],
          "Floor Plan Analysis": {
            "floor_plans": {
              "A1": {
                "count": 4,
                "avg_sqft": 936,
                "bedrooms": 1,
                "bathrooms": 1,
                "base_floor_plan": "A1",
                "renovation_status": "not_specified",
                "bed_bath_confidence": "medium"
              },
              "A2": {
                "count": 2,
                "avg_sqft": 936,
                "bedrooms": 2,
                "bathrooms": 1,
                "base_floor_plan": "A2",
                "renovation_status": "not_specified",
                "bed_bath_confidence": "medium"
              },
              "B1": {
                "count": 3,
                "avg_sqft": 1238,
                "bedrooms": 2,
                "bathrooms": 1,
                "base_floor_plan": "B1",
                "renovation_status": "not_specified",
                "bed_bath_confidence": "medium"
              },
              "B2": {
                "count": 3,
                "avg_sqft": 1238,
                "bedrooms": 2,
                "bathrooms": 2,
                "base_floor_plan": "B2",
                "renovation_status": "not_specified",
                "bed_bath_confidence": "medium"
              }
            }
          },
          "Property Information": null,
          "Mapping for the charges": {
            "Monthly Rent": ["RENT"],
            "other_charges": ["Unit Upgrades", "WASH/DRY"],
            "utility_reimbursement": ["WATER"]
          }
        }
      },
      "status": "completed",
      "processId": "f0325b31-10fc-401d-bf1c-507bea69b8ec",
      "documentId": "0ba54f65-a0dd-4f38-97d0-e9ee328b64b7",
      "extractedAt": "2025-12-15T07:34:40.535124+00:00"
    },
    "error_message": null,
    "created_at": {},
    "updated_at": {},
    "deleted_at": null
  }
};
