/**
 * Sample Data for InvestAssist Application
 *
 * This file contains all hardcoded/sample data used throughout the application.
 * Replace these values with actual API calls or database queries in production.
 *
 * @module sample-data
 */

import type { PropertyData, ProFormaLineItem, MonthlyData } from "./property-data"

/**
 * Generate realistic monthly data with seasonal variations
 * @param annual - Annual total amount
 * @param variance - Variance factor (0-1) for seasonal fluctuation
 * @returns Monthly breakdown object
 */
export function generateMonthlyData(annual: number, variance = 0.05): MonthlyData {
  const monthly = annual / 12
  return {
    jan: monthly * (1 - variance),
    feb: monthly * (1 - variance * 0.5),
    mar: monthly * (1 + variance * 0.3),
    apr: monthly * (1 + variance * 0.5),
    may: monthly * (1 + variance * 0.8),
    jun: monthly * (1 + variance),
    jul: monthly * (1 + variance * 0.8),
    aug: monthly * (1 + variance * 0.5),
    sep: monthly * (1 + variance * 0.3),
    oct: monthly * (1 - variance * 0.3),
    nov: monthly * (1 - variance * 0.5),
    dec: monthly * (1 - variance),
  }
}

/**
 * Generate sample Pro Forma data for a property
 * This function creates realistic financial projections based on property characteristics
 *
 * @param units - Number of units in the property
 * @param marketRent - Average market rent per unit
 * @returns Complete Pro Forma data structure
 */
export function generateSampleProFormaData(units: number, marketRent: number) {
  return {
    income: {
      rentalIncome: [
        {
          id: "market-rent",
          label: "Market Rent",
          category: "RENTAL_INCOME",
          t12Actual: marketRent * units * 12,
          underwritten: marketRent * units * 12,
          year1: marketRent * units * 12 * 1.03,
          percentOfEGI: 100,
          variance: 3.0,
          notes: "Market rent based on comparable properties",
          monthlyData: generateMonthlyData(marketRent * units * 12),
          isEditable: true,
        },
        {
          id: "loss-to-lease",
          label: "Loss/Gain to Lease",
          category: "RENTAL_INCOME",
          t12Actual: -50 * units * 12,
          underwritten: -30 * units * 12,
          year1: 0,
          percentOfEGI: -2.5,
          variance: -100,
          notes: "Current vs market rent gap, expected to close",
          monthlyData: generateMonthlyData(-50 * units * 12),
          isEditable: true,
        },
        {
          id: "vacancy-loss",
          label: "Vacancy Loss",
          category: "VACANCY_LOSS",
          t12Actual: -marketRent * units * 12 * 0.07,
          underwritten: -marketRent * units * 12 * 0.05,
          year1: -marketRent * units * 12 * 0.05,
          percentOfEGI: -5.0,
          variance: 0,
          notes: "5% stabilized vacancy assumption",
          monthlyData: generateMonthlyData(-marketRent * units * 12 * 0.05),
          isEditable: true,
        },
        {
          id: "concessions",
          label: "Rent Concessions",
          category: "CONCESSIONS",
          t12Actual: -40 * units * 12,
          underwritten: -25 * units * 12,
          year1: -15 * units * 12,
          percentOfEGI: -1.5,
          variance: -40,
          notes: "Move-in specials, declining as market improves",
          monthlyData: generateMonthlyData(-25 * units * 12),
          isEditable: true,
        },
        {
          id: "bad-debt",
          label: "Bad Debt",
          category: "BAD_DEBT",
          t12Actual: -15 * units * 12,
          underwritten: -10 * units * 12,
          year1: -10 * units * 12,
          percentOfEGI: -0.5,
          variance: 0,
          notes: "Collection loss reserve",
          monthlyData: generateMonthlyData(-10 * units * 12),
          isEditable: true,
        },
        {
          id: "net-rental-income",
          label: "NET RENTAL INCOME",
          formula: "= Market Rent + Loss/Gain + Vacancy + Concessions + Bad Debt",
          category: "",
          t12Actual: marketRent * units * 12 * 0.88,
          underwritten: marketRent * units * 12 * 0.92,
          year1: marketRent * units * 12 * 0.95,
          percentOfEGI: 91.0,
          variance: 3.3,
          notes: "",
          isSubtotal: true,
          isBold: true,
        },
      ] as ProFormaLineItem[],
      otherIncome: [
        {
          id: "parking",
          label: "Parking",
          category: "PARKING",
          t12Actual: 75 * units * 12,
          underwritten: 80 * units * 12,
          year1: 85 * units * 12,
          percentOfEGI: 4.0,
          variance: 6.25,
          notes: "Covered parking fees",
          monthlyData: generateMonthlyData(80 * units * 12),
          isEditable: true,
        },
        {
          id: "storage",
          label: "Storage",
          category: "MISC_INCOME",
          t12Actual: 25 * units * 12,
          underwritten: 30 * units * 12,
          year1: 30 * units * 12,
          percentOfEGI: 1.5,
          variance: 0,
          notes: "Storage unit rentals",
          monthlyData: generateMonthlyData(30 * units * 12),
          isEditable: true,
        },
        {
          id: "pet-fees",
          label: "Pet Fees",
          category: "OTHER_FEES",
          t12Actual: 35 * units * 12,
          underwritten: 40 * units * 12,
          year1: 45 * units * 12,
          percentOfEGI: 2.0,
          variance: 12.5,
          notes: "Pet rent and deposits",
          monthlyData: generateMonthlyData(40 * units * 12),
          isEditable: true,
        },
        {
          id: "utilities",
          label: "Utility Reimbursements",
          category: "RUBS",
          t12Actual: 50 * units * 12,
          underwritten: 55 * units * 12,
          year1: 60 * units * 12,
          percentOfEGI: 2.75,
          variance: 9.1,
          notes: "RUBS and utility reimbursements",
          monthlyData: generateMonthlyData(55 * units * 12),
          isEditable: true,
        },
        {
          id: "application-fees",
          label: "Application Fees",
          category: "APPLICATION_FEES",
          t12Actual: 15 * units * 12,
          underwritten: 18 * units * 12,
          year1: 20 * units * 12,
          percentOfEGI: 0.9,
          variance: 11.1,
          notes: "Application and admin fees",
          monthlyData: generateMonthlyData(18 * units * 12),
          isEditable: true,
        },
        {
          id: "late-fees",
          label: "Late Fees",
          category: "LATE_FEES",
          t12Actual: 10 * units * 12,
          underwritten: 12 * units * 12,
          year1: 12 * units * 12,
          percentOfEGI: 0.6,
          variance: 0,
          notes: "Late payment fees",
          monthlyData: generateMonthlyData(12 * units * 12),
          isEditable: true,
        },
        {
          id: "total-other-income",
          label: "TOTAL OTHER INCOME",
          formula: "= SUM(Parking + Storage + Pet Fees + Utilities + Application + Late Fees)",
          category: "",
          t12Actual: 210 * units * 12,
          underwritten: 235 * units * 12,
          year1: 252 * units * 12,
          percentOfEGI: 11.75,
          variance: 7.2,
          notes: "",
          isSubtotal: true,
          isBold: true,
        },
      ] as ProFormaLineItem[],
      recoveries: [] as ProFormaLineItem[],
    },
    expenses: {
      controllable: [
        {
          id: "repairs-maintenance",
          label: "Repairs & Maintenance",
          category: "REPAIRS",
          t12Actual: 350 * units * 12,
          underwritten: 320 * units * 12,
          year1: 330 * units * 12,
          percentOfEGI: 15.5,
          variance: 3.1,
          notes: "General repairs and maintenance",
          monthlyData: generateMonthlyData(320 * units * 12, 0.1),
          isEditable: true,
        },
        {
          id: "turnover",
          label: "Unit Turnovers",
          category: "TURNOVER",
          t12Actual: 200 * units * 12,
          underwritten: 180 * units * 12,
          year1: 185 * units * 12,
          percentOfEGI: 8.5,
          variance: 2.8,
          notes: "Make-ready costs",
          monthlyData: generateMonthlyData(180 * units * 12, 0.15),
          isEditable: true,
        },
        {
          id: "utilities",
          label: "Utilities",
          category: "UTILITIES",
          t12Actual: 180 * units * 12,
          underwritten: 190 * units * 12,
          year1: 200 * units * 12,
          percentOfEGI: 9.0,
          variance: 5.3,
          notes: "Water, electric, gas for common areas",
          monthlyData: generateMonthlyData(190 * units * 12, 0.12),
          isEditable: true,
        },
        {
          id: "payroll",
          label: "Payroll",
          category: "PAYROLL",
          t12Actual: 280 * units * 12,
          underwritten: 290 * units * 12,
          year1: 305 * units * 12,
          percentOfEGI: 14.0,
          variance: 5.2,
          notes: "Staff salaries and benefits",
          monthlyData: generateMonthlyData(290 * units * 12, 0.02),
          isEditable: true,
        },
        {
          id: "marketing",
          label: "Marketing & Advertising",
          category: "MARKETING",
          t12Actual: 70 * units * 12,
          underwritten: 65 * units * 12,
          year1: 65 * units * 12,
          percentOfEGI: 3.0,
          variance: 0,
          notes: "Marketing and leasing costs",
          monthlyData: generateMonthlyData(65 * units * 12, 0.08),
          isEditable: true,
        },
        {
          id: "admin",
          label: "General & Administrative",
          category: "ADMIN",
          t12Actual: 95 * units * 12,
          underwritten: 100 * units * 12,
          year1: 105 * units * 12,
          percentOfEGI: 4.75,
          variance: 5.0,
          notes: "Office, supplies, software",
          monthlyData: generateMonthlyData(100 * units * 12, 0.05),
          isEditable: true,
        },
        {
          id: "contract-services",
          label: "Contract Services",
          category: "CONTRACTS",
          t12Actual: 120 * units * 12,
          underwritten: 125 * units * 12,
          year1: 130 * units * 12,
          percentOfEGI: 6.0,
          variance: 4.0,
          notes: "HVAC, elevator, pool maintenance",
          monthlyData: generateMonthlyData(125 * units * 12, 0.1),
          isEditable: true,
        },
      ] as ProFormaLineItem[],
      nonControllable: [
        {
          id: "insurance",
          label: "Insurance",
          category: "INSURANCE",
          t12Actual: 100 * units * 12,
          underwritten: 115 * units * 12,
          year1: 125 * units * 12,
          percentOfEGI: 5.5,
          variance: 8.7,
          notes: "Property and liability insurance",
          monthlyData: generateMonthlyData(115 * units * 12, 0.02),
          isEditable: true,
        },
        {
          id: "real-estate-tax",
          label: "Real Estate Taxes",
          category: "REAL_ESTATE_TAX",
          t12Actual: 220 * units * 12,
          underwritten: 230 * units * 12,
          year1: 240 * units * 12,
          percentOfEGI: 11.0,
          variance: 4.3,
          notes: "Property taxes",
          monthlyData: generateMonthlyData(230 * units * 12, 0.01),
          isEditable: true,
        },
        {
          id: "management-fee",
          label: "Management Fees",
          category: "MANAGEMENT",
          t12Actual: marketRent * units * 12 * 0.03,
          underwritten: marketRent * units * 12 * 0.03,
          year1: marketRent * units * 12 * 0.03 * 1.03,
          percentOfEGI: 3.0,
          variance: 2.9,
          notes: "3% of EGI",
          monthlyData: generateMonthlyData(marketRent * units * 12 * 0.03),
          isEditable: true,
        },
        {
          id: "other-expenses",
          label: "Other Expenses",
          category: "OTHER",
          t12Actual: 40 * units * 12,
          underwritten: 45 * units * 12,
          year1: 48 * units * 12,
          percentOfEGI: 2.0,
          variance: 6.7,
          notes: "Miscellaneous expenses",
          monthlyData: generateMonthlyData(45 * units * 12, 0.1),
          isEditable: true,
        },
        {
          id: "total-operating-expenses",
          label: "TOTAL OPERATING EXPENSES",
          formula: "= SUM(All Operating Expense Categories)",
          category: "",
          t12Actual: marketRent * units * 12 * 0.42,
          underwritten: marketRent * units * 12 * 0.41,
          year1: marketRent * units * 12 * 0.42,
          percentOfEGI: 40.0,
          variance: 2.4,
          notes: "",
          isSubtotal: true,
          isBold: true,
        },
      ] as ProFormaLineItem[],
    },
    capital: {
      items: [
        {
          id: "replacement-reserves",
          label: "Replacement Reserves",
          category: "REPLACEMENT_RESERVES",
          t12Actual: -35 * units * 12,
          underwritten: -35 * units * 12,
          year1: -35 * units * 12,
          percentOfEGI: -1.75,
          variance: 0,
          notes: "$300/unit/year reserve",
          monthlyData: generateMonthlyData(-35 * units * 12, 0),
          isEditable: true,
        },
        {
          id: "capex",
          label: "Capital Improvements",
          category: "CAPITAL_IMPROVEMENTS",
          t12Actual: -50 * units * 12,
          underwritten: -40 * units * 12,
          year1: -45 * units * 12,
          percentOfEGI: -2.0,
          variance: 12.5,
          notes: "Major capital improvements",
          monthlyData: generateMonthlyData(-40 * units * 12, 0.2),
          isEditable: true,
        },
      ] as ProFormaLineItem[],
    },
    debtService: {
      items: [
        {
          id: "debt-service",
          label: "Debt Service",
          category: "DEBT_SERVICE",
          t12Actual: -marketRent * units * 12 * 0.35,
          underwritten: -marketRent * units * 12 * 0.35,
          year1: -marketRent * units * 12 * 0.35,
          percentOfEGI: -35.0,
          variance: 0,
          notes: "Principal + Interest payments",
          monthlyData: generateMonthlyData(-marketRent * units * 12 * 0.35, 0),
          isEditable: true,
        },
        {
          id: "net-cash-flow",
          label: "NET CASH FLOW",
          formula: "= NOI - Capital Expenses - Debt Service",
          category: "",
          t12Actual: marketRent * units * 12 * 0.17,
          underwritten: marketRent * units * 12 * 0.23,
          year1: marketRent * units * 12 * 0.24,
          percentOfEGI: 21.25,
          variance: 4.3,
          notes: "",
          isSubtotal: true,
          isBold: true,
        },
      ] as ProFormaLineItem[],
    },
  }
}

/**
 * Sample property data for demonstration
 * Replace with actual API calls in production
 */
export const SAMPLE_PROPERTIES: PropertyData[] = [
  {
    id: "1",
    name: "Downtown Heights",
    address: "1247 Broadway Avenue, Austin, TX 78701",
    type: "Multifamily",
    units: 120,
    yearBuilt: 2018,
    squareFeet: 95000,
    occupancy: 92,
    avgRent: 2100,
    noi: 2850000,
    capRate: 5.2,
    purchasePrice: 54800000,
    loanAmount: 38360000,
    ltv: 70,
    interestRate: 4.25,
    loanTerm: 10,
    status: "active",
    imageUrl: "/modern-apartment-building.png",
    unitMix: [
      { type: "Studio", count: 20, avgRent: 1500, sqft: 550 },
      { type: "1 Bed", count: 50, avgRent: 1900, sqft: 750 },
      { type: "2 Bed", count: 40, avgRent: 2500, sqft: 1050 },
      { type: "3 Bed", count: 10, avgRent: 3200, sqft: 1350 },
    ],
  },
  // Add more sample properties as needed
]
